// frontend/vue-app/src/features/task-board/modal/TaskModal.vue
<template>
  <Modal
    :isOpen="isModalOpen"
    @close="onModalClose"
    title="Create task"
    description="Add new task to your list"
  >
    <TaskForm @submit="onSubmit" />
  </Modal>
</template>

<script setup lang="ts">
import type { CreateTaskPayload } from '@entities/task/model'
import Modal from '@shared/ui/modal.vue'
import { inject, ref } from 'vue'
import { isModalOpenKey, onModalCloseKey } from '../constants'
import TaskForm from '../form/TaskForm.vue'

const onSubmit = (formData: CreateTaskPayload) => {
  console.log({ formData })
  // createTask(formData) // TODO
  onModalClose?.()
}

const isModalOpen = inject(isModalOpenKey) ?? ref(false)
const onModalClose = inject(onModalCloseKey)
</script>

<style scoped></style>

// frontend/react-app/src/features/task-board/modal/TaskModal.tsx
import type { CreateTaskPayload } from '@entities/task/model'
import { Modal } from '@shared/ui/modal'
import { TaskForm } from '../form/TaskForm'
import { useCreateTask } from '../hooks/useCreateTask'

interface TaskModalProps {
	isOpen?: boolean
	onVisibilityChange?: (state: boolean) => void
	usePortal?: boolean
	portalTarget?: string
}

export function TaskModal({ isOpen, onVisibilityChange }: TaskModalProps) {
	const { mutate: createTask } = useCreateTask()

	const onSubmit = (formData: CreateTaskPayload) => {
		console.log({ formData })
		createTask(formData)
		onVisibilityChange?.(false)
	}

	return (
		<Modal
			isOpen={isOpen}
			onModalVisibilityChange={onVisibilityChange}
			usePortal
			portalTarget='#modal-root'
		>
			<Modal.Content
				title='Create task'
				description='Add new task to your list'
			>
				<TaskForm onSubmit={onSubmit} />
			</Modal.Content>
		</Modal>
	)
}
