// frontend/react-app/src/shared/ui/input/Input.tsx
import { useId } from 'react'

interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {
	label?: string
}

export function Input(props: InputProps) {
	const { label } = props

	const id = useId()

	return (
		<div className='flex flex-col justify-center items-stretch flex-1 basis-10'>
			{label && (
				<label className='' htmlFor={id}>
					{label}
				</label>
			)}
			<input
				className='border border-blue-200 outline-blue-200 rounded-md px-4 py-2 h-full'
				id={id}
				{...props}
			/>
		</div>
	)
}

// frontend/vue-app/src/shared/ui/input.vue
<template>
  <div className="flex flex-col justify-center items-stretch flex-1 basis-10">
    <label v-if="label" :for="id">{{ label }}</label>

    <input
      class="border border-blue-200 outline-blue-200 rounded-md px-4 py-2 h-full"
      :id="id"
      v-bind="bindAttrs"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, useAttrs, type InputHTMLAttributes } from 'vue'

interface InputProps {
  label?: string
}

const props = defineProps<InputProps>()
const attrs = useAttrs() as InputHTMLAttributes

const bindAttrs = computed(() => {
  return {
    ...attrs,
    ...props,
  }
})

const id = `input-${Math.random().toString(36).slice(2, 9)}`
</script>

<style scoped></style>
