// frontend/react-app/src/features/task-board/ui/TaskFilter.tsx
import Select, { type Props as SelectProps } from 'react-select'

export const options = [
	{ value: undefined, label: 'All tasks' },
	{ value: true, label: 'Completed' },
	{ value: false, label: 'In progress' }
]

export function TaskFilters(props: SelectProps) {
	return (
		<div>
			<Select
				options={options}
				placeholder='Filters'
				classNames={{
					control: () => '!border-blue-200'
				}}
				{...props}
			/>
		</div>
	)
}

// frontend/vue-app/src/features/task-board/ui/TaskFilter.vue
<template>
  <select class="border border-blue-200 rounded-md p-2 outline-0">
    <option v-for="option in options" :key="option.label" :value="option.value">
      {{ option.label }}
    </option>
  </select>
</template>

<script setup lang="ts">
interface SelectProps {
  value: boolean | undefined
  label: string
}

const options: SelectProps[] = [
  { value: undefined, label: 'All tasks' },
  { value: true, label: 'Completed' },
  { value: false, label: 'In progress' },
]
</script>

<style scoped></style>
